// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caserver.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sign struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey" json:"publicKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Nonce                string   `protobuf:"bytes,5,opt,name=nonce" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sign) Reset()         { *m = Sign{} }
func (m *Sign) String() string { return proto.CompactTextString(m) }
func (*Sign) ProtoMessage()    {}
func (*Sign) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{0}
}
func (m *Sign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sign.Unmarshal(m, b)
}
func (m *Sign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sign.Marshal(b, m, deterministic)
}
func (dst *Sign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign.Merge(dst, src)
}
func (m *Sign) XXX_Size() int {
	return xxx_messageInfo_Sign.Size(m)
}
func (m *Sign) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign.DiscardUnknown(m)
}

var xxx_messageInfo_Sign proto.InternalMessageInfo

func (m *Sign) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Sign) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Sign) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Sign) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type EnrollNetRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Net                  string   `protobuf:"bytes,4,opt,name=net" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollNetRequest) Reset()         { *m = EnrollNetRequest{} }
func (m *EnrollNetRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollNetRequest) ProtoMessage()    {}
func (*EnrollNetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{1}
}
func (m *EnrollNetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollNetRequest.Unmarshal(m, b)
}
func (m *EnrollNetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollNetRequest.Marshal(b, m, deterministic)
}
func (dst *EnrollNetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollNetRequest.Merge(dst, src)
}
func (m *EnrollNetRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollNetRequest.Size(m)
}
func (m *EnrollNetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollNetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollNetRequest proto.InternalMessageInfo

func (m *EnrollNetRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *EnrollNetRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *EnrollNetRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EnrollNetRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

type EnrollNodeRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Net                  string   `protobuf:"bytes,4,opt,name=net" json:"net,omitempty"`
	AdminAddress         string   `protobuf:"bytes,5,opt,name=adminAddress" json:"adminAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollNodeRequest) Reset()         { *m = EnrollNodeRequest{} }
func (m *EnrollNodeRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollNodeRequest) ProtoMessage()    {}
func (*EnrollNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{2}
}
func (m *EnrollNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollNodeRequest.Unmarshal(m, b)
}
func (m *EnrollNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollNodeRequest.Marshal(b, m, deterministic)
}
func (dst *EnrollNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollNodeRequest.Merge(dst, src)
}
func (m *EnrollNodeRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollNodeRequest.Size(m)
}
func (m *EnrollNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollNodeRequest proto.InternalMessageInfo

func (m *EnrollNodeRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *EnrollNodeRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *EnrollNodeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EnrollNodeRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *EnrollNodeRequest) GetAdminAddress() string {
	if m != nil {
		return m.AdminAddress
	}
	return ""
}

type EnrollResponse struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollResponse) Reset()         { *m = EnrollResponse{} }
func (m *EnrollResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollResponse) ProtoMessage()    {}
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{3}
}
func (m *EnrollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollResponse.Unmarshal(m, b)
}
func (m *EnrollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollResponse.Marshal(b, m, deterministic)
}
func (dst *EnrollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollResponse.Merge(dst, src)
}
func (m *EnrollResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollResponse.Size(m)
}
func (m *EnrollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollResponse proto.InternalMessageInfo

func (m *EnrollResponse) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

// The request message of  Get Current Cert
type CurrentCertRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Net                  string   `protobuf:"bytes,3,opt,name=net" json:"net,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentCertRequest) Reset()         { *m = CurrentCertRequest{} }
func (m *CurrentCertRequest) String() string { return proto.CompactTextString(m) }
func (*CurrentCertRequest) ProtoMessage()    {}
func (*CurrentCertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{4}
}
func (m *CurrentCertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentCertRequest.Unmarshal(m, b)
}
func (m *CurrentCertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentCertRequest.Marshal(b, m, deterministic)
}
func (dst *CurrentCertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentCertRequest.Merge(dst, src)
}
func (m *CurrentCertRequest) XXX_Size() int {
	return xxx_messageInfo_CurrentCertRequest.Size(m)
}
func (m *CurrentCertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentCertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentCertRequest proto.InternalMessageInfo

func (m *CurrentCertRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *CurrentCertRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *CurrentCertRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *CurrentCertRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CurrentCertResponse struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	CaCert               string   `protobuf:"bytes,2,opt,name=caCert" json:"caCert,omitempty"`
	Cert                 string   `protobuf:"bytes,3,opt,name=cert" json:"cert,omitempty"`
	PrivateKey           string   `protobuf:"bytes,4,opt,name=privateKey" json:"privateKey,omitempty"`
	NodeHdPriKey         string   `protobuf:"bytes,5,opt,name=nodeHdPriKey" json:"nodeHdPriKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentCertResponse) Reset()         { *m = CurrentCertResponse{} }
func (m *CurrentCertResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentCertResponse) ProtoMessage()    {}
func (*CurrentCertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{5}
}
func (m *CurrentCertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentCertResponse.Unmarshal(m, b)
}
func (m *CurrentCertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentCertResponse.Marshal(b, m, deterministic)
}
func (dst *CurrentCertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentCertResponse.Merge(dst, src)
}
func (m *CurrentCertResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentCertResponse.Size(m)
}
func (m *CurrentCertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentCertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentCertResponse proto.InternalMessageInfo

func (m *CurrentCertResponse) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *CurrentCertResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *CurrentCertResponse) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *CurrentCertResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *CurrentCertResponse) GetNodeHdPriKey() string {
	if m != nil {
		return m.NodeHdPriKey
	}
	return ""
}

type RevokeListRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Net                  string   `protobuf:"bytes,3,opt,name=net" json:"net,omitempty"`
	SerialNum            string   `protobuf:"bytes,4,opt,name=serial_num,json=serialNum" json:"serial_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeListRequest) Reset()         { *m = RevokeListRequest{} }
func (m *RevokeListRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeListRequest) ProtoMessage()    {}
func (*RevokeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{6}
}
func (m *RevokeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeListRequest.Unmarshal(m, b)
}
func (m *RevokeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeListRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeListRequest.Merge(dst, src)
}
func (m *RevokeListRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeListRequest.Size(m)
}
func (m *RevokeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeListRequest proto.InternalMessageInfo

func (m *RevokeListRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *RevokeListRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *RevokeListRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *RevokeListRequest) GetSerialNum() string {
	if m != nil {
		return m.SerialNum
	}
	return ""
}

type RevokeListResponse struct {
	Logid                string        `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	List                 []*RevokeNode `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RevokeListResponse) Reset()         { *m = RevokeListResponse{} }
func (m *RevokeListResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeListResponse) ProtoMessage()    {}
func (*RevokeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{7}
}
func (m *RevokeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeListResponse.Unmarshal(m, b)
}
func (m *RevokeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeListResponse.Marshal(b, m, deterministic)
}
func (dst *RevokeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeListResponse.Merge(dst, src)
}
func (m *RevokeListResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeListResponse.Size(m)
}
func (m *RevokeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeListResponse proto.InternalMessageInfo

func (m *RevokeListResponse) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *RevokeListResponse) GetList() []*RevokeNode {
	if m != nil {
		return m.List
	}
	return nil
}

type RevokeNode struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SerialNum            string   `protobuf:"bytes,2,opt,name=serialNum" json:"serialNum,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	PublicKey            string   `protobuf:"bytes,5,opt,name=publicKey" json:"publicKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeNode) Reset()         { *m = RevokeNode{} }
func (m *RevokeNode) String() string { return proto.CompactTextString(m) }
func (*RevokeNode) ProtoMessage()    {}
func (*RevokeNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{8}
}
func (m *RevokeNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeNode.Unmarshal(m, b)
}
func (m *RevokeNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeNode.Marshal(b, m, deterministic)
}
func (dst *RevokeNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeNode.Merge(dst, src)
}
func (m *RevokeNode) XXX_Size() int {
	return xxx_messageInfo_RevokeNode.Size(m)
}
func (m *RevokeNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeNode.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeNode proto.InternalMessageInfo

func (m *RevokeNode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RevokeNode) GetSerialNum() string {
	if m != nil {
		return m.SerialNum
	}
	return ""
}

func (m *RevokeNode) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RevokeNode) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RevokeNode) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RevokeNode) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RevokeNodeRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Net                  string   `protobuf:"bytes,3,opt,name=net" json:"net,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeNodeRequest) Reset()         { *m = RevokeNodeRequest{} }
func (m *RevokeNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeNodeRequest) ProtoMessage()    {}
func (*RevokeNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{9}
}
func (m *RevokeNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeNodeRequest.Unmarshal(m, b)
}
func (m *RevokeNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeNodeRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeNodeRequest.Merge(dst, src)
}
func (m *RevokeNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeNodeRequest.Size(m)
}
func (m *RevokeNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeNodeRequest proto.InternalMessageInfo

func (m *RevokeNodeRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *RevokeNodeRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *RevokeNodeRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *RevokeNodeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RevokeNodeResponse struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeNodeResponse) Reset()         { *m = RevokeNodeResponse{} }
func (m *RevokeNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeNodeResponse) ProtoMessage()    {}
func (*RevokeNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{10}
}
func (m *RevokeNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeNodeResponse.Unmarshal(m, b)
}
func (m *RevokeNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeNodeResponse.Marshal(b, m, deterministic)
}
func (dst *RevokeNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeNodeResponse.Merge(dst, src)
}
func (m *RevokeNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeNodeResponse.Size(m)
}
func (m *RevokeNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeNodeResponse proto.InternalMessageInfo

func (m *RevokeNodeResponse) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

type DecryptByHdKeyRequest struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Net                  string   `protobuf:"bytes,4,opt,name=net" json:"net,omitempty"`
	ChildHdpubKey        string   `protobuf:"bytes,5,opt,name=childHdpubKey" json:"childHdpubKey,omitempty"`
	CypherText           string   `protobuf:"bytes,6,opt,name=cypherText" json:"cypherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptByHdKeyRequest) Reset()         { *m = DecryptByHdKeyRequest{} }
func (m *DecryptByHdKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptByHdKeyRequest) ProtoMessage()    {}
func (*DecryptByHdKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{11}
}
func (m *DecryptByHdKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptByHdKeyRequest.Unmarshal(m, b)
}
func (m *DecryptByHdKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptByHdKeyRequest.Marshal(b, m, deterministic)
}
func (dst *DecryptByHdKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptByHdKeyRequest.Merge(dst, src)
}
func (m *DecryptByHdKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DecryptByHdKeyRequest.Size(m)
}
func (m *DecryptByHdKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptByHdKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptByHdKeyRequest proto.InternalMessageInfo

func (m *DecryptByHdKeyRequest) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *DecryptByHdKeyRequest) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *DecryptByHdKeyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DecryptByHdKeyRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *DecryptByHdKeyRequest) GetChildHdpubKey() string {
	if m != nil {
		return m.ChildHdpubKey
	}
	return ""
}

func (m *DecryptByHdKeyRequest) GetCypherText() string {
	if m != nil {
		return m.CypherText
	}
	return ""
}

type DecryptByHdKeyResponse struct {
	Logid                string   `protobuf:"bytes,1,opt,name=logid" json:"logid,omitempty"`
	RealMsg              string   `protobuf:"bytes,2,opt,name=realMsg" json:"realMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptByHdKeyResponse) Reset()         { *m = DecryptByHdKeyResponse{} }
func (m *DecryptByHdKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DecryptByHdKeyResponse) ProtoMessage()    {}
func (*DecryptByHdKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caserver_599a3469424089b9, []int{12}
}
func (m *DecryptByHdKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptByHdKeyResponse.Unmarshal(m, b)
}
func (m *DecryptByHdKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptByHdKeyResponse.Marshal(b, m, deterministic)
}
func (dst *DecryptByHdKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptByHdKeyResponse.Merge(dst, src)
}
func (m *DecryptByHdKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DecryptByHdKeyResponse.Size(m)
}
func (m *DecryptByHdKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptByHdKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptByHdKeyResponse proto.InternalMessageInfo

func (m *DecryptByHdKeyResponse) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *DecryptByHdKeyResponse) GetRealMsg() string {
	if m != nil {
		return m.RealMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Sign)(nil), "pb.Sign")
	proto.RegisterType((*EnrollNetRequest)(nil), "pb.EnrollNetRequest")
	proto.RegisterType((*EnrollNodeRequest)(nil), "pb.EnrollNodeRequest")
	proto.RegisterType((*EnrollResponse)(nil), "pb.EnrollResponse")
	proto.RegisterType((*CurrentCertRequest)(nil), "pb.CurrentCertRequest")
	proto.RegisterType((*CurrentCertResponse)(nil), "pb.CurrentCertResponse")
	proto.RegisterType((*RevokeListRequest)(nil), "pb.RevokeListRequest")
	proto.RegisterType((*RevokeListResponse)(nil), "pb.RevokeListResponse")
	proto.RegisterType((*RevokeNode)(nil), "pb.RevokeNode")
	proto.RegisterType((*RevokeNodeRequest)(nil), "pb.RevokeNodeRequest")
	proto.RegisterType((*RevokeNodeResponse)(nil), "pb.RevokeNodeResponse")
	proto.RegisterType((*DecryptByHdKeyRequest)(nil), "pb.DecryptByHdKeyRequest")
	proto.RegisterType((*DecryptByHdKeyResponse)(nil), "pb.DecryptByHdKeyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Caserver service

type CaserverClient interface {
	// Net Admin Enroll
	NetAdminEnroll(ctx context.Context, in *EnrollNetRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Node Enroll
	NodeEnroll(ctx context.Context, in *EnrollNodeRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Get Current Cert
	GetCurrentCert(ctx context.Context, in *CurrentCertRequest, opts ...grpc.CallOption) (*CurrentCertResponse, error)
	// Get Revoke List
	GetRevokeList(ctx context.Context, in *RevokeListRequest, opts ...grpc.CallOption) (*RevokeListResponse, error)
	// Revoke a node
	RevokeCert(ctx context.Context, in *RevokeNodeRequest, opts ...grpc.CallOption) (*RevokeNodeResponse, error)
	// decryptByHdKey
	DecryptByHdKey(ctx context.Context, in *DecryptByHdKeyRequest, opts ...grpc.CallOption) (*DecryptByHdKeyResponse, error)
}

type caserverClient struct {
	cc *grpc.ClientConn
}

func NewCaserverClient(cc *grpc.ClientConn) CaserverClient {
	return &caserverClient{cc}
}

func (c *caserverClient) NetAdminEnroll(ctx context.Context, in *EnrollNetRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	out := new(EnrollResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/NetAdminEnroll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caserverClient) NodeEnroll(ctx context.Context, in *EnrollNodeRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	out := new(EnrollResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/NodeEnroll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caserverClient) GetCurrentCert(ctx context.Context, in *CurrentCertRequest, opts ...grpc.CallOption) (*CurrentCertResponse, error) {
	out := new(CurrentCertResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/GetCurrentCert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caserverClient) GetRevokeList(ctx context.Context, in *RevokeListRequest, opts ...grpc.CallOption) (*RevokeListResponse, error) {
	out := new(RevokeListResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/GetRevokeList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caserverClient) RevokeCert(ctx context.Context, in *RevokeNodeRequest, opts ...grpc.CallOption) (*RevokeNodeResponse, error) {
	out := new(RevokeNodeResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/RevokeCert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caserverClient) DecryptByHdKey(ctx context.Context, in *DecryptByHdKeyRequest, opts ...grpc.CallOption) (*DecryptByHdKeyResponse, error) {
	out := new(DecryptByHdKeyResponse)
	err := grpc.Invoke(ctx, "/pb.Caserver/DecryptByHdKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Caserver service

type CaserverServer interface {
	// Net Admin Enroll
	NetAdminEnroll(context.Context, *EnrollNetRequest) (*EnrollResponse, error)
	// Node Enroll
	NodeEnroll(context.Context, *EnrollNodeRequest) (*EnrollResponse, error)
	// Get Current Cert
	GetCurrentCert(context.Context, *CurrentCertRequest) (*CurrentCertResponse, error)
	// Get Revoke List
	GetRevokeList(context.Context, *RevokeListRequest) (*RevokeListResponse, error)
	// Revoke a node
	RevokeCert(context.Context, *RevokeNodeRequest) (*RevokeNodeResponse, error)
	// decryptByHdKey
	DecryptByHdKey(context.Context, *DecryptByHdKeyRequest) (*DecryptByHdKeyResponse, error)
}

func RegisterCaserverServer(s *grpc.Server, srv CaserverServer) {
	s.RegisterService(&_Caserver_serviceDesc, srv)
}

func _Caserver_NetAdminEnroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollNetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).NetAdminEnroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/NetAdminEnroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).NetAdminEnroll(ctx, req.(*EnrollNetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caserver_NodeEnroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).NodeEnroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/NodeEnroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).NodeEnroll(ctx, req.(*EnrollNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caserver_GetCurrentCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).GetCurrentCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/GetCurrentCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).GetCurrentCert(ctx, req.(*CurrentCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caserver_GetRevokeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).GetRevokeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/GetRevokeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).GetRevokeList(ctx, req.(*RevokeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caserver_RevokeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).RevokeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/RevokeCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).RevokeCert(ctx, req.(*RevokeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caserver_DecryptByHdKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptByHdKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaserverServer).DecryptByHdKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Caserver/DecryptByHdKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaserverServer).DecryptByHdKey(ctx, req.(*DecryptByHdKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Caserver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Caserver",
	HandlerType: (*CaserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NetAdminEnroll",
			Handler:    _Caserver_NetAdminEnroll_Handler,
		},
		{
			MethodName: "NodeEnroll",
			Handler:    _Caserver_NodeEnroll_Handler,
		},
		{
			MethodName: "GetCurrentCert",
			Handler:    _Caserver_GetCurrentCert_Handler,
		},
		{
			MethodName: "GetRevokeList",
			Handler:    _Caserver_GetRevokeList_Handler,
		},
		{
			MethodName: "RevokeCert",
			Handler:    _Caserver_RevokeCert_Handler,
		},
		{
			MethodName: "DecryptByHdKey",
			Handler:    _Caserver_DecryptByHdKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caserver.proto",
}

func init() { proto.RegisterFile("caserver.proto", fileDescriptor_caserver_599a3469424089b9) }

var fileDescriptor_caserver_599a3469424089b9 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xfa, 0x93, 0x69, 0x1b, 0xb5, 0x4b, 0x9b, 0x9a, 0xa8, 0xa0, 0x6a, 0x85, 0x50,
	0xd5, 0x43, 0x23, 0x95, 0x1b, 0x27, 0x4a, 0x40, 0x0d, 0x2a, 0x44, 0x95, 0xe9, 0x1d, 0x39, 0xf6,
	0x28, 0x5d, 0xe1, 0xac, 0xcd, 0xee, 0xa6, 0x6a, 0xae, 0xbc, 0x02, 0x07, 0x0e, 0xdc, 0x79, 0x0b,
	0x9e, 0x82, 0x0b, 0x0f, 0xc0, 0x83, 0xa0, 0x5d, 0xaf, 0x6b, 0x3b, 0x49, 0x23, 0xa1, 0xa2, 0xde,
	0xbc, 0xdf, 0xee, 0xce, 0xf7, 0xcd, 0xb7, 0x33, 0x63, 0x68, 0x86, 0x81, 0x44, 0x71, 0x85, 0xe2,
	0x28, 0x15, 0x89, 0x4a, 0x48, 0x2d, 0x1d, 0xb4, 0xf7, 0x86, 0x49, 0x32, 0x8c, 0xb1, 0x13, 0xa4,
	0xac, 0x13, 0x70, 0x9e, 0xa8, 0x40, 0xb1, 0x84, 0xcb, 0xec, 0x04, 0xbd, 0x84, 0xfa, 0x07, 0x36,
	0xe4, 0xc4, 0x83, 0x95, 0x20, 0x8a, 0x04, 0x4a, 0xe9, 0x39, 0xfb, 0xce, 0x41, 0xc3, 0xcf, 0x97,
	0x64, 0x0f, 0x1a, 0xe9, 0x78, 0x10, 0xb3, 0xf0, 0x0c, 0x27, 0x5e, 0xcd, 0xec, 0x15, 0x00, 0x21,
	0x50, 0x97, 0x6c, 0xc8, 0x3d, 0x77, 0xdf, 0x39, 0x58, 0xf7, 0xcd, 0x37, 0xd9, 0x86, 0x25, 0x9e,
	0xf0, 0x10, 0xbd, 0x25, 0x73, 0x3a, 0x5b, 0x50, 0x01, 0x9b, 0x6f, 0xb8, 0x48, 0xe2, 0xb8, 0x8f,
	0xca, 0xc7, 0xcf, 0x63, 0x94, 0x4a, 0x9f, 0x8c, 0x93, 0x21, 0x8b, 0x2c, 0x67, 0xb6, 0x20, 0x7b,
	0x36, 0xa6, 0x26, 0x5b, 0x3b, 0x5e, 0x3d, 0x4a, 0x07, 0x47, 0x5a, 0xa3, 0x8d, 0x5e, 0x52, 0xea,
	0x56, 0x95, 0x6e, 0x82, 0xcb, 0x51, 0x79, 0x75, 0x83, 0xea, 0x4f, 0xfa, 0xcd, 0x81, 0x2d, 0x4b,
	0x9a, 0x44, 0x78, 0x4f, 0xac, 0x84, 0xc2, 0x7a, 0x10, 0x8d, 0x18, 0x3f, 0xb1, 0x17, 0x32, 0x1b,
	0x2a, 0x18, 0x7d, 0x06, 0xcd, 0x4c, 0x98, 0x8f, 0x32, 0x4d, 0xb8, 0xc4, 0xf9, 0xaa, 0xa8, 0x02,
	0xd2, 0x1d, 0x0b, 0x81, 0x5c, 0x75, 0x51, 0xdc, 0xc9, 0x37, 0xab, 0xd3, 0x2d, 0x74, 0x96, 0x72,
	0xaa, 0x57, 0x72, 0xa2, 0xdf, 0x1d, 0x78, 0x58, 0xa1, 0x5d, 0xa4, 0x91, 0xb4, 0x60, 0x39, 0x0c,
	0xf4, 0x39, 0x5b, 0x1e, 0x76, 0xa5, 0x6b, 0x23, 0xd4, 0x68, 0x46, 0x69, 0xbe, 0xc9, 0x13, 0x80,
	0x54, 0xb0, 0xab, 0x40, 0xa1, 0x2e, 0xa7, 0x8c, 0xb6, 0x84, 0x68, 0xef, 0x78, 0x12, 0x61, 0x2f,
	0x3a, 0x17, 0x4c, 0x9f, 0xb0, 0xde, 0x95, 0x31, 0x7a, 0x0d, 0x5b, 0x3e, 0x5e, 0x25, 0x9f, 0xf0,
	0x1d, 0x93, 0xff, 0xd9, 0x92, 0xc7, 0x00, 0x12, 0x05, 0x0b, 0xe2, 0x8f, 0x7c, 0x3c, 0xb2, 0xf2,
	0x1a, 0x19, 0xd2, 0x1f, 0x8f, 0x68, 0x1f, 0x48, 0x99, 0x79, 0xa1, 0x2b, 0x14, 0xea, 0x31, 0x93,
	0xda, 0x13, 0xf7, 0x60, 0xed, 0xb8, 0xa9, 0xa9, 0xb3, 0xbb, 0xa6, 0x14, 0xcd, 0x1e, 0xfd, 0xe1,
	0x00, 0x14, 0x20, 0x69, 0x42, 0xcd, 0x46, 0x71, 0xfd, 0x9a, 0x51, 0x5f, 0x70, 0xe7, 0xad, 0x77,
	0x03, 0x68, 0x2b, 0x43, 0x81, 0x81, 0xc2, 0x0b, 0x36, 0x42, 0x93, 0x84, 0xeb, 0x97, 0x90, 0xdb,
	0x9f, 0xb7, 0xda, 0xd2, 0x4b, 0xb7, 0xb5, 0xf4, 0x72, 0xd1, 0xd2, 0x54, 0xe6, 0x96, 0xdf, 0xb5,
	0x8f, 0xfe, 0xa5, 0x0a, 0x0f, 0x73, 0xb7, 0x33, 0xd2, 0x85, 0x7d, 0xf2, 0xd3, 0x81, 0x9d, 0xd7,
	0x18, 0x8a, 0x49, 0xaa, 0x5e, 0x4d, 0x7a, 0xd1, 0x19, 0x4e, 0xee, 0xab, 0xdb, 0x9f, 0xc2, 0x46,
	0x78, 0xc9, 0xe2, 0xa8, 0x17, 0xa5, 0xe3, 0x41, 0x61, 0x68, 0x15, 0x34, 0x8f, 0x35, 0x49, 0x2f,
	0x51, 0x5c, 0xe0, 0xb5, 0x32, 0xd6, 0x36, 0xfc, 0x12, 0x42, 0x7b, 0xd0, 0x9a, 0x96, 0xbf, 0xb0,
	0xba, 0x3c, 0x58, 0x11, 0x18, 0xc4, 0xef, 0xe5, 0xd0, 0x16, 0x46, 0xbe, 0x3c, 0xfe, 0xed, 0xc2,
	0x6a, 0xd7, 0xfe, 0x06, 0x88, 0x0f, 0xcd, 0x3e, 0xaa, 0x13, 0x3d, 0x79, 0xb2, 0x71, 0x43, 0xb6,
	0x75, 0xaa, 0xd3, 0x83, 0xb8, 0x4d, 0x0a, 0x34, 0x27, 0xa6, 0xad, 0x2f, 0xbf, 0xfe, 0x7c, 0xad,
	0x6d, 0xd2, 0xb5, 0x0e, 0x47, 0xd5, 0x41, 0xb3, 0xf9, 0xc2, 0x39, 0x24, 0xe7, 0x00, 0xfa, 0x41,
	0x6c, 0xbc, 0x9d, 0x52, 0xbc, 0xa2, 0x36, 0xe6, 0x06, 0xdc, 0x35, 0x01, 0xb7, 0xe8, 0x7a, 0x47,
	0xb7, 0x73, 0x29, 0x62, 0x17, 0x9a, 0xa7, 0xa8, 0x4a, 0x03, 0x87, 0xb4, 0xf4, 0xf5, 0xd9, 0xc1,
	0xd7, 0xde, 0x9d, 0xc1, 0x6d, 0xec, 0x07, 0xe4, 0x25, 0x6c, 0x9c, 0xea, 0x84, 0xf2, 0xf6, 0xcc,
	0x94, 0xcd, 0x0c, 0x8a, 0x76, 0x6b, 0x1a, 0xbe, 0x89, 0x70, 0x91, 0x37, 0xa3, 0x91, 0xb0, 0x33,
	0xd5, 0xb1, 0xb3, 0xd7, 0xcb, 0x65, 0x39, 0x9d, 0x9c, 0x30, 0x27, 0x74, 0x72, 0x6f, 0xa1, 0x59,
	0x7d, 0x59, 0xf2, 0x48, 0x87, 0x98, 0x5b, 0xac, 0xed, 0xf6, 0xbc, 0xad, 0x5c, 0xe0, 0x60, 0xd9,
	0xfc, 0xb3, 0x9f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xea, 0x60, 0x93, 0x79, 0xe7, 0x07, 0x00,
	0x00,
}
